export { default as coke } from './bebida-coke.webp'
export { default as fanta } from './bebida-fanta.webp'
export { default as inca } from './bebida-inca.webp'
export { default as sprite } from './bebida-sprite.webp'
export { default as pepsi } from './bebida.pepsi.webp'