name: Deploy and Test Pipeline

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production
  schedule:
    - cron: "0 */2 * * *"

jobs:
  check-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Check deployment status
        run: |
          URL="https://burgercat.netlify.app"
          if curl --silent --fail "$URL"; then
            echo "La página está funcionando correctamente."
            STATUS="✅ La página está funcionando correctamente."
          else
            echo "Error: La página no está disponible."
            STATUS="❌ La página no está disponible."
            exit 1
          fi

      - name: Update README with page status
        run: |
          CURRENT_TIME=$(date '+%Y-%m-%d %H:%M:%S')  # Obtener la hora actual
          echo "## Prueba de estado de la página\n" >> README.md
          echo "$CURRENT_TIME - $STATUS" >> README.md

      - name: Commit changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add README.md
          git commit -m "Actualización del estado de la página" || echo "No hay cambios para hacer commit."
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/vngerus/BurgerCat_DevOps_Projects.git
