name: Check Website Status

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  check-website-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check deployment status
        run: |
          URL="https://burgercat.netlify.app"

          if curl --silent --fail "$URL"; then
            STATUS="La página está funcionando correctamente."
          else
            STATUS="Error: La página no está disponible."
          fi

          # Obtener la fecha y hora actual
          CURRENT_TIME=$(date '+%Y-%m-%d %H:%M:%S')

          # Imprimir el resultado en la consola
          echo "$CURRENT_TIME - $STATUS"

          # Agregar el resultado al README.md
          echo "$CURRENT_TIME - $STATUS" >> README.md

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Actualización del estado de la página: $CURRENT_TIME" || echo "No hay cambios para hacer commit."

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/vngerus/BurgerCat_DevOps_Projects.git || echo "No se pudo hacer push, revisa si hubo algún cambio pendiente."
