name: Deploy and Test Pipeline

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production
  schedule:
    - cron: '0 */2 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          npm test > test-results.txt
        continue-on-error: true

      - name: Check deployment status
        run: |
          URL="https://burgercat.netlify.app"
          
          if curl --silent --fail "$URL"; then
            echo "La página está funcionando correctamente."
          else
            echo "Error: La página no está disponible."
            exit 1
          fi

      - name: Update README with test results
        run: |
          TEST_RESULTS=$(cat test-results.txt | sed 's/$/\\n/g')
          CURRENT_TIME=$(date '+%Y-%m-%d %H:%M:%S')
          sed -i '/<!-- TEST RESULTS START -->/,/<!-- TEST RESULTS END -->/c\<!-- TEST RESULTS START -->\n'"$CURRENT_TIME - $TEST_RESULTS"'\n<!-- TEST RESULTS END -->' README.md

      - name: Commit changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add README.md
          git commit -m "test: se añaden resultados de los testeos con jest creados por pipeline"
          git push
