name: Deploy and Test Pipeline

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production
  schedule:
    - cron: "0 */2 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Check deployment status
        id: check_status
        run: |
          URL="https://burgercat.netlify.app"
          if curl --silent --fail "$URL"; then
            echo "La página está funcionando correctamente."
            echo "status=success" >> $GITHUB_ENV  # Define el estado como success
          else
            echo "Error: La página no está disponible."
            echo "status=fail" >> $GITHUB_ENV  # Define el estado como fail
            exit 1
          fi

      - name: Update README with status
        run: |
          STATUS="${{ env.status }}"
          CURRENT_TIME=$(date '+%Y-%m-%d %H:%M:%S')  # Obtener la hora actual

          if [ "$STATUS" == "success" ]; then
            STATUS_MARK="✅ La página está funcionando bien."
          else
            STATUS_MARK="❌ La página se encuentra caída."
          fi

          # Actualizar el README.md
          sed -i "/## Prueba de estado de la pagina:/a \ \n- $CURRENT_TIME: $STATUS_MARK" README.md

      - name: Commit changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add README.md
          git commit -m "Actualización del estado de la página" || echo "No hay cambios para hacer commit."
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/vngerus/BurgerCat_DevOps_Projects.git
